const translations={
  es:{skip:'Saltar al contenido',navAbout:'Sobre mí',navSkills:'Habilidades',navProjects:'Proyectos',navContact:'Contacto',heroEyebrow:'Hola, soy',heroRole:'Desarrollador Backend Java en formación',heroDescription:'Analista Universitario en Sistemas de Computación y estudiante avanzado de Licenciatura en Informática, enfocado en Java, Spring Boot, APIs REST y bases de datos MySQL. Construyo aplicaciones orientadas a resolver problemas reales y sigo fortaleciendo mis conocimientos de arquitectura backend.',viewProjects:'Ver proyectos',downloadCv:'Ver CV',availability:'Abierto a oportunidades junior',aboutEyebrow:'Conocé mi perfil',aboutTitle:'Sobre mí',aboutText1:'Mi objetivo profesional es desarrollarme como Java Backend Developer. Durante la carrera trabajé en aplicaciones de escritorio, sistemas conectados a MySQL, diseño orientado a objetos, procesos ETL, pruebas y proyectos académicos de arquitectura de software.',aboutText2:'Actualmente continúo profundizando Spring Boot, desarrollo de APIs REST, persistencia con JPA/Hibernate, seguridad y buenas prácticas. Me interesa escribir código claro, comprender cómo funciona cada componente y convertir requisitos concretos en soluciones mantenibles.',educationTitle:'Formación',educationText:'Analista Universitario en Sistemas de Computación\nLicenciatura en Informática — en curso',focusTitle:'Especialización',focusText:'Java Backend\nSpring Boot y MySQL',skillsEyebrow:'Tecnologías y conocimientos',skillsTitle:'Habilidades',backendTitle:'Backend y Java',databaseTitle:'Bases de datos',toolsTitle:'Herramientas y fundamentos',otherTitle:'Experiencia complementaria',projectsEyebrow:'Aplicaciones y trabajos destacados',projectsTitle:'Proyectos',hotelTitle:'Sistema de gestión hotelera',hotelText:'Aplicación Java Swing con MySQL para gestionar usuarios, huéspedes, habitaciones, reservas, pagos, facturación, disponibilidad y reportes. Implementa arquitectura MVC, DAO, validaciones y principios de POO.',ocrTitle:'Aplicación OCR para Android',ocrText:'Aplicación móvil que captura imágenes, reconoce texto y permite reutilizar el contenido obtenido. Desarrollada con CameraX, ML Kit y una interfaz moderna para Android.',quizTitle:'Generador de exámenes',quizText:'Programa con interfaz gráfica que carga preguntas desde archivos de texto, genera evaluaciones de verdadero o falso y opción múltiple, corrige respuestas y muestra la solución correcta.',githubNote:'Podés consultar mis repositorios públicos y próximos proyectos en GitHub.',visitGithub:'Visitar GitHub',contactEyebrow:'Hablemos',contactTitle:'Contacto',contactText:'Estoy interesado en oportunidades como desarrollador Java junior, prácticas profesionales y proyectos donde pueda seguir aprendiendo y aportar valor.',openProfile:'Abrir perfil profesional',viewRepositories:'Ver repositorios',backTop:'Volver arriba ↑'},
  en:{skip:'Skip to content',navAbout:'About',navSkills:'Skills',navProjects:'Projects',navContact:'Contact',heroEyebrow:'Hello, I am',heroRole:'Java Backend Developer in training',heroDescription:'University Analyst in Computer Systems and advanced Computer Science degree student focused on Java, Spring Boot, REST APIs and MySQL databases. I build applications aimed at solving real problems while continuing to strengthen my backend architecture skills.',viewProjects:'View projects',downloadCv:'View résumé',availability:'Open to junior opportunities',aboutEyebrow:'Get to know my profile',aboutTitle:'About me',aboutText1:'My professional goal is to grow as a Java Backend Developer. Throughout my degree I have worked on desktop applications, MySQL-connected systems, object-oriented design, ETL processes, testing and academic software architecture projects.',aboutText2:'I am currently deepening my knowledge of Spring Boot, REST API development, persistence with JPA/Hibernate, security and best practices. I enjoy writing clear code, understanding how each component works and turning concrete requirements into maintainable solutions.',educationTitle:'Education',educationText:'University Analyst in Computer Systems\nComputer Science degree — in progress',focusTitle:'Specialization',focusText:'Java Backend\nSpring Boot and MySQL',skillsEyebrow:'Technologies and knowledge',skillsTitle:'Skills',backendTitle:'Backend and Java',databaseTitle:'Databases',toolsTitle:'Tools and fundamentals',otherTitle:'Additional experience',projectsEyebrow:'Featured applications and work',projectsTitle:'Projects',hotelTitle:'Hotel management system',hotelText:'Java Swing and MySQL application for managing users, guests, rooms, bookings, payments, invoices, availability and reports. It uses MVC, DAO, validations and OOP principles.',ocrTitle:'Android OCR application',ocrText:'Mobile application that captures images, recognizes text and lets users reuse the extracted content. Built with CameraX, ML Kit and a modern Android interface.',quizTitle:'Exam generator',quizText:'Desktop application that loads questions from text files, generates true-or-false and multiple-choice tests, checks answers and displays the correct solution.',githubNote:'You can explore my public repositories and upcoming projects on GitHub.',visitGithub:'Visit GitHub',contactEyebrow:'Let’s talk',contactTitle:'Contact',contactText:'I am interested in junior Java developer opportunities, internships and projects where I can continue learning and add value.',openProfile:'Open professional profile',viewRepositories:'View repositories',backTop:'Back to top ↑'}
};

const body=document.body;
const themeButton=document.querySelector('#theme-toggle');
const langButton=document.querySelector('#lang-toggle');
const menuButton=document.querySelector('.menu-toggle');
const navMenu=document.querySelector('#nav-menu');

function setTheme(theme){body.classList.toggle('dark',theme==='dark');localStorage.setItem('portfolio-theme',theme);document.querySelectorAll('[data-light]').forEach(img=>img.src=theme==='dark'?img.dataset.dark:img.dataset.light);themeButton.textContent=theme==='dark'?'☀':'◐';themeButton.setAttribute('aria-label',theme==='dark'?'Activar tema claro':'Activar tema oscuro')}
function setLanguage(lang){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const value=translations[lang][el.dataset.i18n];if(value)el.innerText=value});langButton.textContent=lang==='es'?'EN':'ES';localStorage.setItem('portfolio-lang',lang);document.title=lang==='es'?'Erik Ovejero | Desarrollador Backend Java':'Erik Ovejero | Java Backend Developer'}

setTheme(localStorage.getItem('portfolio-theme')||((window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'));
setLanguage(localStorage.getItem('portfolio-lang')||'es');

themeButton.addEventListener('click',()=>setTheme(body.classList.contains('dark')?'light':'dark'));
langButton.addEventListener('click',()=>setLanguage(document.documentElement.lang==='es'?'en':'es'));
menuButton.addEventListener('click',()=>{const open=navMenu.classList.toggle('open');menuButton.classList.toggle('open',open);menuButton.setAttribute('aria-expanded',String(open))});
document.querySelectorAll('.nav-menu a').forEach(link=>link.addEventListener('click',()=>{navMenu.classList.remove('open');menuButton.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
document.querySelector('#current-year').textContent=new Date().getFullYear();

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
